// Smart Scheduling Service for Calendar App
// Generates study plans based on proficiency data and reading history

// Get optimal study schedule based on proficiency data
export const generateStudyPlan = (options) => {
  const {
    proficiencyData = {},
    settings = {},
    existingEvents = [],
    startDate = new Date(),
    daysToGenerate = 7,
  } = options;

  const {
    schoolClosingTime = '15:00',
    studyDuration = 60,
    breakDuration = 15,
    weekendStudy = true,
  } = settings;

  const plan = [];
  const [closingHour, closingMinute] = schoolClosingTime.split(':').map(Number);

  // Sort topics by proficiency (lowest first)
  const sortedTopics = Object.entries(proficiencyData)
    .map(([key, data]) => ({
      key,
      subject: data.subject,
      topic: data.topic,
      proficiency: data.proficiencyLevel || 0,
      lastReviewed: data.lastUpdated,
    }))
    .sort((a, b) => a.proficiency - b.proficiency);

  // If no proficiency data, use default subjects
  const defaultSubjects = [
    { subject: 'Mathematics', topic: 'Algebra', proficiency: 50 },
    { subject: 'Physics', topic: 'Motion & Forces', proficiency: 50 },
    { subject: 'Chemistry', topic: 'Atomic Structure', proficiency: 50 },
    { subject: 'Biology', topic: 'Cell Structure', proficiency: 50 },
    { subject: 'English', topic: 'Grammar', proficiency: 50 },
  ];

  const topicsToSchedule = sortedTopics.length > 0 ? sortedTopics : defaultSubjects;

  // Generate study sessions for each day
  for (let day = 0; day < daysToGenerate; day++) {
    const currentDate = new Date(startDate);
    currentDate.setDate(currentDate.getDate() + day);

    const dayOfWeek = currentDate.getDay();
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;

    // Skip weekends if not enabled
    if (isWeekend && !weekendStudy) continue;

    // Calculate available study time slots
    let startHour = isWeekend ? 10 : closingHour + 1; // Start 1 hour after school
    let endHour = 21; // End by 9 PM

    // Check for existing events on this day
    const dateStr = currentDate.toISOString().split('T')[0];
    const dayEvents = existingEvents.filter(e =>
      e.date && e.date.startsWith(dateStr)
    );

    // Create study blocks
    let currentHour = startHour;
    let sessionCount = 0;
    const maxSessionsPerDay = isWeekend ? 4 : 3;

    while (currentHour < endHour && sessionCount < maxSessionsPerDay) {
      // Select topic for this session (rotate through topics)
      const topicIndex = (day * maxSessionsPerDay + sessionCount) % topicsToSchedule.length;
      const topic = topicsToSchedule[topicIndex];

      // Check for conflicts with existing events
      const sessionStart = new Date(currentDate);
      sessionStart.setHours(currentHour, 0, 0, 0);

      const sessionEnd = new Date(sessionStart);
      sessionEnd.setMinutes(sessionEnd.getMinutes() + studyDuration);

      const hasConflict = dayEvents.some(event => {
        const eventStart = new Date(event.date);
        const eventEnd = new Date(event.endDate || eventStart);
        return (sessionStart < eventEnd && sessionEnd > eventStart);
      });

      if (!hasConflict) {
        // Calculate priority based on proficiency
        const priority = topic.proficiency < 40 ? 'high' :
                        topic.proficiency < 70 ? 'medium' : 'low';

        plan.push({
          id: `study_${dateStr}_${sessionCount}`,
          type: 'study',
          title: `Study: ${topic.topic}`,
          subject: topic.subject,
          topic: topic.topic,
          date: sessionStart.toISOString(),
          endDate: sessionEnd.toISOString(),
          duration: studyDuration,
          priority,
          proficiencyLevel: topic.proficiency,
          isAutoGenerated: true,
          color: getSubjectColor(topic.subject),
          reminder: true,
          status: 'scheduled',
        });

        sessionCount++;
      }

      // Move to next time slot (study duration + break)
      currentHour += Math.ceil((studyDuration + breakDuration) / 60);
    }
  }

  return plan;
};

// Calculate spaced repetition intervals
export const calculateReviewInterval = (proficiency, consecutiveCorrect = 0) => {
  // Base interval in days
  let interval = 1;

  if (proficiency >= 90) {
    interval = 14; // Review in 2 weeks
  } else if (proficiency >= 80) {
    interval = 7; // Review in 1 week
  } else if (proficiency >= 70) {
    interval = 4; // Review in 4 days
  } else if (proficiency >= 60) {
    interval = 2; // Review in 2 days
  } else {
    interval = 1; // Review tomorrow
  }

  // Adjust based on consecutive correct answers
  interval = Math.min(interval * (1 + consecutiveCorrect * 0.2), 30);

  return Math.round(interval);
};

// Get color for subject
export const getSubjectColor = (subject) => {
  const colors = {
    Mathematics: '#3498db',
    Physics: '#9b59b6',
    Chemistry: '#e74c3c',
    Biology: '#27ae60',
    English: '#f39c12',
    default: '#4a90d9',
  };
  return colors[subject] || colors.default;
};

// Analyze study patterns
export const analyzeStudyPatterns = (events, studyDates = []) => {
  const analysis = {
    mostProductiveHours: [],
    totalStudyTime: 0,
    averageSessionLength: 0,
    subjectDistribution: {},
    weekdayDistribution: {
      0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0,
    },
    adherenceRate: 0,
  };

  const studyEvents = events.filter(e => e.type === 'study' && e.status === 'completed');

  if (studyEvents.length === 0) {
    return analysis;
  }

  // Calculate total study time and average session length
  let totalMinutes = 0;
  const hourCounts = {};

  studyEvents.forEach(event => {
    const duration = event.duration || 60;
    totalMinutes += duration;

    // Track hours
    const hour = new Date(event.date).getHours();
    hourCounts[hour] = (hourCounts[hour] || 0) + 1;

    // Track subjects
    if (event.subject) {
      analysis.subjectDistribution[event.subject] =
        (analysis.subjectDistribution[event.subject] || 0) + duration;
    }

    // Track weekdays
    const dayOfWeek = new Date(event.date).getDay();
    analysis.weekdayDistribution[dayOfWeek] += duration;
  });

  analysis.totalStudyTime = totalMinutes;
  analysis.averageSessionLength = Math.round(totalMinutes / studyEvents.length);

  // Find most productive hours
  const sortedHours = Object.entries(hourCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([hour]) => parseInt(hour));
  analysis.mostProductiveHours = sortedHours;

  // Calculate adherence rate
  const scheduledEvents = events.filter(e =>
    e.type === 'study' && e.isAutoGenerated && new Date(e.date) < new Date()
  );
  const completedScheduled = scheduledEvents.filter(e => e.status === 'completed');
  analysis.adherenceRate = scheduledEvents.length > 0
    ? Math.round((completedScheduled.length / scheduledEvents.length) * 100)
    : 0;

  return analysis;
};

// Get study recommendations
export const getStudyRecommendations = (proficiencyData, recentSessions = []) => {
  const recommendations = [];

  // Find weak topics
  const weakTopics = Object.entries(proficiencyData)
    .filter(([_, data]) => data.proficiencyLevel < 50)
    .sort((a, b) => a[1].proficiencyLevel - b[1].proficiencyLevel)
    .slice(0, 3);

  weakTopics.forEach(([key, data]) => {
    recommendations.push({
      type: 'weak_topic',
      title: `Focus on ${data.topic}`,
      description: `Your proficiency in ${data.topic} (${data.subject}) is ${data.proficiencyLevel}%. Consider dedicating more time to this topic.`,
      subject: data.subject,
      topic: data.topic,
      priority: 'high',
    });
  });

  // Check for topics not reviewed recently
  const oneWeekAgo = new Date(Date.now() - 7 * 86400000);
  Object.entries(proficiencyData).forEach(([key, data]) => {
    if (data.lastUpdated && new Date(data.lastUpdated) < oneWeekAgo) {
      recommendations.push({
        type: 'review_needed',
        title: `Review ${data.topic}`,
        description: `It's been over a week since you reviewed ${data.topic}. A quick review session can help retention.`,
        subject: data.subject,
        topic: data.topic,
        priority: 'medium',
      });
    }
  });

  // Balance recommendations
  const subjectCounts = {};
  Object.entries(proficiencyData).forEach(([_, data]) => {
    subjectCounts[data.subject] = (subjectCounts[data.subject] || 0) + 1;
  });

  const minSubjectCount = Math.min(...Object.values(subjectCounts));
  Object.entries(subjectCounts).forEach(([subject, count]) => {
    if (count === minSubjectCount) {
      recommendations.push({
        type: 'balance',
        title: `Explore more ${subject}`,
        description: `You have fewer ${subject} topics in your study plan. Consider adding more content.`,
        subject,
        priority: 'low',
      });
    }
  });

  return recommendations.slice(0, 5);
};

// Get today's schedule
export const getTodaySchedule = (events) => {
  const today = new Date();
  const todayStr = today.toISOString().split('T')[0];

  return events
    .filter(e => e.date && e.date.startsWith(todayStr))
    .sort((a, b) => new Date(a.date) - new Date(b.date));
};

// Get upcoming events
export const getUpcomingEvents = (events, days = 7) => {
  const now = new Date();
  const futureDate = new Date(now.getTime() + days * 86400000);

  return events
    .filter(e => {
      const eventDate = new Date(e.date);
      return eventDate >= now && eventDate <= futureDate;
    })
    .sort((a, b) => new Date(a.date) - new Date(b.date));
};
