import React, { createContext, useContext, useState, useEffect } from 'react';
import * as Storage from '../utils/storage';
import * as Scheduler from '../services/scheduler';

const AppContext = createContext();

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useApp must be used within AppProvider');
  }
  return context;
};

export const AppProvider = ({ children }) => {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);
  const [settings, setSettings] = useState({});
  const [events, setEvents] = useState([]);
  const [studyPlan, setStudyPlan] = useState(null);
  const [goals, setGoals] = useState({});
  const [streaks, setStreaks] = useState({});
  const [proficiencyData, setProficiencyData] = useState({});
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [viewMode, setViewMode] = useState('month'); // month, week, day

  useEffect(() => {
    loadInitialData();
  }, []);

  const loadInitialData = async () => {
    try {
      setLoading(true);

      const [
        savedProfile,
        savedSettings,
        savedEvents,
        savedPlan,
        savedGoals,
        savedStreaks,
        importedProficiency,
        importedReaderData,
      ] = await Promise.all([
        Storage.getUserProfile(),
        Storage.getSettings(),
        Storage.getEvents(),
        Storage.getStudyPlan(),
        Storage.getGoals(),
        Storage.getStreaks(),
        Storage.importProficiencyData(),
        Storage.importReaderData(),
      ]);

      if (!savedProfile && importedReaderData?.profile) {
        await Storage.saveUserProfile(importedReaderData.profile);
        setUser(importedReaderData.profile);
      } else {
        setUser(savedProfile);
      }

      setSettings(savedSettings);
      setEvents(savedEvents);
      setStudyPlan(savedPlan);
      setGoals(savedGoals);
      setStreaks(savedStreaks);

      if (importedProficiency?.proficiency) {
        setProficiencyData(importedProficiency.proficiency);
      }
    } catch (error) {
      console.error('Error loading initial data:', error);
    } finally {
      setLoading(false);
    }
  };

  // User functions
  const registerUser = async (name, classGrade) => {
    const profile = {
      name,
      classGrade,
      registeredAt: new Date().toISOString(),
    };
    await Storage.saveUserProfile(profile);
    setUser(profile);
    return true;
  };

  // Settings functions
  const updateSettings = async (newSettings) => {
    const merged = { ...settings, ...newSettings };
    await Storage.saveSettings(merged);
    setSettings(merged);
    return true;
  };

  // Event functions
  const addEvent = async (event) => {
    const eventId = await Storage.addEvent(event);
    if (eventId) {
      setEvents(prev => [...prev, { ...event, id: eventId, createdAt: new Date().toISOString() }]);
    }
    return eventId;
  };

  const updateEvent = async (eventId, updates) => {
    const success = await Storage.updateEvent(eventId, updates);
    if (success) {
      setEvents(prev => prev.map(e => e.id === eventId ? { ...e, ...updates } : e));
    }
    return success;
  };

  const deleteEvent = async (eventId) => {
    const success = await Storage.deleteEvent(eventId);
    if (success) {
      setEvents(prev => prev.filter(e => e.id !== eventId));
    }
    return success;
  };

  const completeStudySession = async (eventId) => {
    const success = await updateEvent(eventId, { status: 'completed' });
    if (success) {
      // Update streak
      const updatedStreaks = await Storage.updateStreak();
      if (updatedStreaks) {
        setStreaks(updatedStreaks);
      }

      // Update goals
      const event = events.find(e => e.id === eventId);
      if (event?.duration) {
        const newGoals = { ...goals };
        newGoals.weekly = {
          ...newGoals.weekly,
          currentHours: (newGoals.weekly?.currentHours || 0) + (event.duration / 60),
        };
        newGoals.monthly = {
          ...newGoals.monthly,
          currentHours: (newGoals.monthly?.currentHours || 0) + (event.duration / 60),
        };
        await Storage.saveGoals(newGoals);
        setGoals(newGoals);
      }
    }
    return success;
  };

  // Study Plan functions
  const generateNewStudyPlan = async (daysToGenerate = 7) => {
    const plan = Scheduler.generateStudyPlan({
      proficiencyData,
      settings,
      existingEvents: events,
      startDate: new Date(),
      daysToGenerate,
    });

    // Remove old auto-generated events
    const filteredEvents = events.filter(e => !e.isAutoGenerated);

    // Add new plan events
    const newEvents = [...filteredEvents, ...plan];
    await Storage.saveEvents(newEvents);
    setEvents(newEvents);

    await Storage.saveStudyPlan({ generatedAt: new Date().toISOString(), plan });
    setStudyPlan({ generatedAt: new Date().toISOString(), plan });

    return plan;
  };

  // Goals functions
  const updateGoals = async (newGoals) => {
    const merged = { ...goals, ...newGoals };
    await Storage.saveGoals(merged);
    setGoals(merged);
    return true;
  };

  const resetWeeklyGoal = async () => {
    const newGoals = {
      ...goals,
      weekly: { ...goals.weekly, currentHours: 0 },
    };
    await Storage.saveGoals(newGoals);
    setGoals(newGoals);
  };

  // Analytics functions
  const getStudyAnalytics = () => {
    return Scheduler.analyzeStudyPatterns(events, streaks.studyDates);
  };

  const getRecommendations = () => {
    return Scheduler.getStudyRecommendations(proficiencyData, events);
  };

  const getTodaySchedule = () => {
    return Scheduler.getTodaySchedule(events);
  };

  const getUpcomingEvents = (days = 7) => {
    return Scheduler.getUpcomingEvents(events, days);
  };

  // Sync with other apps
  const syncWithOtherApps = async () => {
    const proficiency = await Storage.importProficiencyData();
    const readerData = await Storage.importReaderData();

    if (proficiency?.proficiency) {
      setProficiencyData(proficiency.proficiency);
    }

    if (readerData?.profile && !user) {
      await Storage.saveUserProfile(readerData.profile);
      setUser(readerData.profile);
    }

    return { proficiency, readerData };
  };

  // Export data
  const exportReport = async () => {
    return await Storage.exportStudyReport();
  };

  // Get events for specific date
  const getEventsForDate = (date) => {
    const dateStr = date.toISOString().split('T')[0];
    return events.filter(e => e.date && e.date.startsWith(dateStr));
  };

  // Get events for week
  const getEventsForWeek = (startDate) => {
    const weekEvents = [];
    for (let i = 0; i < 7; i++) {
      const date = new Date(startDate);
      date.setDate(date.getDate() + i);
      weekEvents.push({
        date,
        events: getEventsForDate(date),
      });
    }
    return weekEvents;
  };

  const value = {
    user,
    loading,
    settings,
    events,
    studyPlan,
    goals,
    streaks,
    proficiencyData,
    selectedDate,
    viewMode,

    setSelectedDate,
    setViewMode,

    registerUser,
    updateSettings,
    addEvent,
    updateEvent,
    deleteEvent,
    completeStudySession,
    generateNewStudyPlan,
    updateGoals,
    resetWeeklyGoal,
    getStudyAnalytics,
    getRecommendations,
    getTodaySchedule,
    getUpcomingEvents,
    getEventsForDate,
    getEventsForWeek,
    syncWithOtherApps,
    exportReport,
  };

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
};
